
export const addrList = [
    {value: "Seoul",label: "서울특별시"},
    {value: "Busan",label: "부산광역시"},
    {value: "Daegu",label: "대구광역시"},
    {value: "Incheon",label: "인천광역시"},
    {value: "Gwangju",label: "광주광역시"},
    {value: "Daejeon",label: "대전광역시"},
    {value: "Ulsan",label: "울산광역시"},
    {value: "Sejong",label: "세종특별자치시"},
    {value: "Gyeonggi-do",label: "경기도"},
    {value: "Chungcheongbuk-do",label: "충청북도"},
    {value: "Chungcheongnam-do",label: "충청남도"},
    {value: "Jeollabuk-do",label: "전라북도"},
    {value: "Jeollanam-do",label: "전라남도"},
    {value: "Gyeongsangbuk-do",label: "경상북도"},
    {value: "Gyeongsangnam-do",label: "경상남도"},
    {value: "Jeju",label: "제주특별자치도"},
    {value: "Gangwon",label: "강원특별자치도"},
]
